name: openwrt-s905x

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Run make-s905x
        run: |
          sudo chmod +x make-s905x
          sudo ./make-s905x
          sudo timedatectl set-timezone Asia/Jakarta
 
      - name: Upload OpenWrt Firmware to Release
        uses: ncipollo/release-action@main
        if: ${{ env.PACKAGED_STATUS }} == 'success' && !cancelled()
        with:
          tag: VincherWrt-21.02.5
          artifacts: "*.img.gz"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
